// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDle9MMBRXyhl0ujVFmosk2RvE0M0HB_2U',
    appId: '1:198394466069:web:7e3723bd4f69055d07631c',
    messagingSenderId: '198394466069',
    projectId: 'easycoffee-4873f',
    authDomain: 'easycoffee-4873f.firebaseapp.com',
    storageBucket: 'easycoffee-4873f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc-C_ztr4qXXlLH18-a_FkEHNzLYbD_dk',
    appId: '1:198394466069:android:bf8a4bed9655c6f507631c',
    messagingSenderId: '198394466069',
    projectId: 'easycoffee-4873f',
    storageBucket: 'easycoffee-4873f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClJHpQIa1gatsbpXfwFaI7wZ8pIuee9Iw',
    appId: '1:198394466069:ios:2008697c35cbf3a407631c',
    messagingSenderId: '198394466069',
    projectId: 'easycoffee-4873f',
    storageBucket: 'easycoffee-4873f.firebasestorage.app',
    iosBundleId: 'com.example.easycoffeeNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClJHpQIa1gatsbpXfwFaI7wZ8pIuee9Iw',
    appId: '1:198394466069:ios:2008697c35cbf3a407631c',
    messagingSenderId: '198394466069',
    projectId: 'easycoffee-4873f',
    storageBucket: 'easycoffee-4873f.firebasestorage.app',
    iosBundleId: 'com.example.easycoffeeNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDle9MMBRXyhl0ujVFmosk2RvE0M0HB_2U',
    appId: '1:198394466069:web:9763ba4853f18bbc07631c',
    messagingSenderId: '198394466069',
    projectId: 'easycoffee-4873f',
    authDomain: 'easycoffee-4873f.firebaseapp.com',
    storageBucket: 'easycoffee-4873f.firebasestorage.app',
  );
}
